version: 2.1

references:
  install-poetry: &install-poetry
    run:
      name: Install Poetry
      command: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  restore-dependencies-cache: &restore-dependencies-cache
    restore_cache:
      keys:
        - deps-py<< parameters.python-version >>-django<< parameters.django-version >>-{{ checksum "poetry.lock" }}
  install-dependencies: &install-dependencies
    run:
      name: Install Dependencies
      command: |
        source $HOME/.poetry/env
        poetry install
        poetry run pip install "django~=<< parameters.django-version >>.0"
  save-dependencies-cache: &save-dependencies-cache
    save_cache:
      key: deps-py<< parameters.python-version >>-django<< parameters.django-version >>-{{ checksum "poetry.lock" }}
      paths:
        - /home/circleci/.cache/pypoetry/virtualenvs
  parametrised-python-executor: &parametrised-python-executor
    parameters:
      python-version:
        type: string
      django-version:
        type: string
    executor:
      name: python
      version: << parameters.python-version >>
  version-matrix: &version-matrix
    matrix:
      parameters:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        django-version: ["2.2", "3.0", "3.1", "3.2", "4.0"]
      exclude:
        - python-version: "3.6"
          django-version: "4.0"
        - python-version: "3.7"
          django-version: "4.0"

executors:
  python:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/python:<< parameters.version >>

jobs:
  build-test:
    <<: *parametrised-python-executor

    steps:
      - checkout

      - *install-poetry
      - *restore-dependencies-cache
      - *install-dependencies
      - *save-dependencies-cache

      - run:
          name: Run Tests
          command: |
            source $HOME/.poetry/env
            poetry run ./runtests

  deploy:
    executor:
      name: python
      version: "3.7"
    steps:
      - checkout
      - run:
          name: Push to PyPI
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            source $HOME/.poetry/env
            poetry publish \
              --build \
              --username "${PYPI_USERNAME}" \
              --password "${PYPI_PASSWORD}" \
              --no-interaction

workflows:
  version: 2.1

  build-test:
    jobs:
      - build-test:
          name: build-test-py<< matrix.python-version >>-Django<< matrix.django-version >>
          <<: *version-matrix

  build-test-deploy:
    jobs:
      - build-test:
          name: build-test-py<< matrix.python-version >>-Django<< matrix.django-version >>
          <<: *version-matrix
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - deploy:
          context: thread-pypi
          requires:
            - build-test
          filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/
